services:
  mysql:
    image: mysql:8.0
    container_name: mormordb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mormorpassword
      MYSQL_DATABASE: MormorDB
      MYSQL_USER: mormor
      MYSQL_PASSWORD: mormorpassword
    ports:
      - '3306:3306'
    volumes:
      - mormordb_data:/var/lib/mysql

  mormordb-api:
    image: mormordb:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - '5299:8080'
    depends_on:
      - mysql

volumes:
  mormordb_data: